spring:
  profiles:
    active:
      - db
  datasource:
    url: jdbc:mysql://localhost:3306/project2db?createDatabaseIfNotExist=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-request-size: 10MB